### ISSUE TITLE
ValueError: Number of samples must be non-negative --- when running _split_normal_aggregator

### ISSUE THREAD

**Issue by elisim** [tarik/pi-snm-qde#1]
Hi Tarik,

Thank you for the great work.

I'm trying to use `_split_normal_aggregator`, but unfortunately I got an error:

```ValueError: Number of samples, -14900, must be non-negative```

I wrote a simple code snippet to reproduce the error:

```python
from split_normal.functions import snm_aggreg
import numpy as np


def main():
    y_pred_all = np.random.rand(5,51,3)
    ans = snm_aggreg(y_pred_all, seed=1)


if __name__ == '__main__':
    main()
```

Thank you for your help,
Eli

**Comment by tarik** [comment]
Hi Eli,

I'm sorry for the late response. Unfortunately, I haven't managed to reproduce the exact same error.

However, the function `snm_aggreg` is missing the `alpha` parameter in the provided example. Additionally, the randomly generated input (most likely) won't have the expected semantics. The triplet values in `y_pred_all` are expected to be in the following order: lower percentile (`y_l`), upper percentile (`y_u`) and the mode (`y_p`), i.e. `y_l < y_p < y_u`.

Hope this helps. :-)

**Comment by tarik** [comment]
Considering as resolved.
